# 当你第一次玩A4，想直接看效果的话：
# 1. 请直接去掉 menu 配置中的  ‘首页’ 和 ‘文章’ 前的 ‘#’ 注释符号
# 2. 请直接去掉 showInMenu 配置中的 ‘- 文章’ 前的 ‘#’ 注释符号
# 3. 执行命令：hexo new page index 生成首页；执行命令：hexo new page list 生成列表页面；
# 4. 执行命令：hexo clean && hexo g && hexo s 直接查看页面效果
menu:
  # 首页: /  #需要hexo new page index,在index/index.md填写的内容将会展现在首页上
  # 文章: /list/ # 需要hexo new page list
  # 添加其他页面格式举例：
  # 关于: /about/ # 需要hexo new page about
  # 标签: /tags/ #需要hexo new page tags
  # 分类: /categories/ # 需要hexo new page categories
  # ...

# 首页你想要展示的menu链接，注意当你修改了menu中的别名，这里要随着更改，不然你会疑惑怎么首页没有修改后的别名
showInMenu:  # menu 中的哪些页面显示在首页中（“首页”必定显示）
  # - 文章  # 将在首页显示 文章 链接
  # - 关于
  # - 标签
  # - 分类

index:  # 首页相关配置
  header:  # 首页的页眉 以及 404页面，当你没开启一言，将会每次刷新页面随机展示下面的语句
    #- "我忘明月很久，明月始终望我"
    #- "人山人海，人来人往"
    #- "看过大海的人不会忘记海的广阔"
    # ...
  hitokoto: false # 一言：调用网络语句展示的接口
  footer: Email:123456789@gmail.com # 除了可以填写任何文字外，可以自动邮箱链接化，但需按照这个格式填写：Email:xxx@gmail.com
  titlePosition: left # center | left  # 首页标题的位置
  width: small  # small | middle | big # 首页的宽度
  list: false # 开启后会在首页展示文章列表

footerLink: # 底部的链接自定义
  info: © 1949-2024 China  # info这个单词不能修改，不想使用可为空
  # 添加链接格式 举例
  # 友链: /friends/ # 需要hexo new page friends
  # 联系: /contact/ # 需要hexo new page contact
  # 支持: /support/ # 需要hexo new page support
  # ...

# 网站备案信息
beian:
  enable: true # 是否启用备案号
  icp: "京ICP备xxxxxxxx号" # 备案号
  url: "https://beian.miit.gov.cn/" # 备案查询链接
  gongan: # 公安备案信息
    enable: false # 是否启用公安备案
    code: "京公网安备xxxxxxxx号" # 公安备案号
    url: "https://beian.miit.gov.cn/" # 公安备案查询链接

post:
  footer: 🌊看过大海的人不会忘记海的广阔🌊
  themeInfo: true # 是否开启底部右侧声明本站信息
  width: middle  #  middle | big
  titlePosition: center # left ｜ center 文章标题的位置

# 相对于source目录下的头像url
favicon: /img/favicon.webp # 默认方形头像
isRoundedAvatar: false # 是否圆形头像
isAvatarRotating: false # 圆形头像是否开启悬浮旋转
displayTitleInTab: false # 是否在浏览器标签页显示文章标题

# 是否启用一些特色工具 false | true
tool:
  darkMode: true # 暗黑模式
  returnToTop: true # 回到顶部按钮
  returnToLast: true # 回退页面按钮
  topToc: true # 文章顶部目录
  leftToc: true # 文章左侧目录 目前仅支持大屏幕浮现
  recentUpdatePost: false # list页面将会新增一个“最近更新”模块，展示最近3篇文章，最近更新可点击跳转至 "最近更新列表页面"
  # A4启动将会自动创建“最近更新页面”：url为 /recent-updates 请自行使用
  # 如果你发现你的最近更新时间总是当天部署的时间，请看 https://ninojay.top/2023/writeByGithub-2/#2024.09.26更新说明


# ---------------------------------------------------------------------------------------
# 以上为基本配置，实现了A4主题追求的纯净风
#
# 以下为 非必要不必更改的配置
#
# ps：还有经过A4作者测试，可供你使用的插件，详见：https://ninojay.top/tags/hexoPlugin/
# ---------------------------------------------------------------------------------------

# 首页页面的其他配置
indexInfo:
  allWordCount: true # 是否显示全站字数统计
  allViewCount: true # 是否显示全站访问量统计

# 文章页面的信息
postInfo:
  updateDate: true # 是否显示文章最近更新时间
  wordCount: true # 是否显示文章字数统计
  readTime: true # 是否显示文章预计阅读耗时
  viewCount: true # 阅读量统计
  prevAndNextLink: # 链接：上一篇和下一篇文章
    status: true # true | false # 设置为true,下面两项才会生效
    prevInfo: 上一篇 # 上一篇提示文案，照顾到英文用户，你可以设置为英语单词
    nextInfo: 下一篇 # 下一篇提示文案，照顾到英文用户，你可以设置为英语单词
  endContent: 以上 # 当你使用了 评论功能，此配置才会生效

# 列表页面的配置
listInfo:
  enable: false
  hoverStyle: underline # box | circle | underline | highlight | strike-through | crossed-off # 鼠标悬浮在文章列表上时的样式
  hoverColor: "#4f7dde" # 鼠标悬浮在文章列表上时的颜色
  animationDuration: 800 # 鼠标悬浮在文章列表上时的动画时长,单位ms毫秒

# 你可能会用到的 https://ninojay.top/hexoplugin/website-cdn/
cdn:
  enable: false # 如果你修改了 css/js ，也许需要把cdn设置为false才会生效
  choose: zzko  # zzko | aliyun | unpkg| jsdelivr  # 都调整为利于国内的cdn，建议使用默认的 zzko 即可
  # 因为是免费CDN，所以有挂的风险，一旦发现网站样式出现原来没有的问题，请尝试关闭CDN

# 实验性功能：A4色调调整：颜色搭配是很主观的行为
# 设置为 false 为 A4 默认灰白色调，可设置为 true 直接启动 体验下 另一种护眼预置色调
# 注：颜色代码需加“#”，颜色单词不需要加“#”
# 更多A4色调搭配推荐：https://ninojay.top/hexoplugin/A4-color-change/
color:
  enable: false # true | false
  font: "#9e5345" # 字体颜色
  background: "#e8e0c9" # 最底部层背景颜色
  indexBackGround: "#efeae2" # 首页层颜色
  postBackGround: "#efeae2" # 文章页层颜色
  codeBackGround: "#e8e0c9" # 代码块背景颜色
  codeFont: "#2e5041" # 代码块字体颜色
  linkBeforeClick: "#2e5041" # 链接点击前的颜色
  linkAfterClick: "#9c9caf" # 链接点击后的颜色

# A4背景引入图片
# 图片你应该先放到 source下，下面选项的图片路径 即为 相对于 source 目录的路径
imageShow:
  enable: false
  background: /img/favicon.webp # 最底部层背景

# A4默认中文使用霞鹜文楷，如果你想关闭这种字体，首先保证enable为 true 接着可以开关对应字体
font:
  enable: false # 是否使用字体开关功能
  LXGWWenKai: true # 霞鹜文楷 如果关闭，中文则使用的是 思源宋体，思源宋体不提供关闭

# 图片幻灯片配置
lightgallery:
  thumbnail: true # 显示缩略图
  zoom: true # 启用缩放功能
  rotate: true # 启用旋转功能能
  autoplay: true # 启用自动播放功能
  fullScreen: true # 启用全屏功能
  pager: false # 页码

# ---------------------------------------------------------------------------------------
# Comment plugin
# 评论插件：需要根据教程自行部署评论服务
# ---------------------------------------------------------------------------------------
comment:
  enable: false
  use: waline # values: waline、twikoo、giscus、artalk

  # Waline
  # See: https://waline.js.org/guide/get-started.html
  waline:
    serverUrl:  # Waline server url(vercel) example: https://example.example.com
    lang: zh-CN # Waline language, default: zh-CN. See: https://waline.js.org/guide/client/i18n.html
    placeholder: 留下你的评论吧。 # 评论框背景信息

  # Twikoo
  # See: https://twikoo.js.org/quick-start.html
  twikoo:
    envId:  # 腾讯云环境填 envId；其它环境填地址
    region:  # 环境地域，默认为 ap-shanghai，腾讯云环境填 ap-shanghai 或 ap-guangzhou；其它环境不填
    lang:  # 用于手动设定评论区语言，支持的语言列表 https://github.com/imaegoo/twikoo/blob/main/src/client/utils/i18n/index.js

  # Giscus
  # See: https://giscus.app
  giscus:
    dataRepo: # data-repo，必填
    dataRepoId: # data-repo-id，必填
    dataCategory: # data-category，选填
    dataCategoryId: # data-category-id，data-mapping="number"时不填，其他情况下必填
    dataMapping: pathname # data-mapping
    dataTerm: # data-term，data-mapping="number"或"specific"时必填，其他情况下不填
    dataStrict: "0" # data-strict
    dataReactionsEnabled: "1" # data-reactions-enabled
    dataEmitMetadata: "0" # data-emit-metadata
    dataInputPosition: bottom # data-input-position
    dataTheme: preferred_color_scheme # data-theme
    dataLang: zh-CN # data-lang
    dataLoading: # data-loading，选填
    crossorigin: anonymous # crossorigin
    async: true # async

  # Artalk
  # See: https://artalk.js.org/guide/deploy.html
  artalk:
    server:  # Artalk 后端地址

inject:
  css: css/custom.css # 找到该文件后，编写你的css样式，每个页面都会自动引入

# 在<head>增加一个<base>元素，仅限有特殊需求者使用：https://developer.mozilla.org/zh-CN/docs/Web/HTML/Reference/Elements/base
baseElement:
  href:
  target:

version: v2.0.1
